
Host nas
  HostName 192.168.5.13
  User root
  Port 22

  PreferredAuthentications publickey
  PubkeyAuthentication yes
  PasswordAuthentication no
  KbdInteractiveAuthentication no

  # 可选：首次连接时更友好（也可改成 yes/no/ask）
  StrictHostKeyChecking accept-new

Host home-router
  HostName 192.168.5.1
  User root
  Port 22

  IdentityFile ~/.ssh/id_ed25519.pub
  IdentitiesOnly yes
  PreferredAuthentications publickey
  PubkeyAuthentication yes
  PasswordAuthentication no
  KbdInteractiveAuthentication no

  StrictHostKeyChecking accept-new

Host nas-waf
  HostName 192.168.5.25
  User root
  Port 22

  PreferredAuthentications publickey
  PubkeyAuthentication yes
  PasswordAuthentication no
  KbdInteractiveAuthentication no

  StrictHostKeyChecking accept-new


Host nas-clawbot
  HostName 192.168.5.30
  User root
  Port 22

  PreferredAuthentications publickey
  PubkeyAuthentication yes
  PasswordAuthentication no
  KbdInteractiveAuthentication no

  # StrictHostKeyChecking accept-new
